import express from "express";
import cors from "cors";
import multer from "multer";
import dotenv from "dotenv";
import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";
import Groq from "groq-sdk";
dotenv.config();
const app=express(); const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024}});
const PORT=process.env.PORT||8080; const MODEL=process.env.GROQ_MODEL||"llama-3.3-70b-versatile";
const keys=[process.env.GROQ_API_KEY,process.env.GROQ_API_KEY_2,process.env.GROQ_API_KEY_3].filter(Boolean);
const allowed=process.env.FRONTEND_URL||"http://localhost:5173";
app.use(cors({origin:allowed==="*"?"*":allowed,methods:["GET","POST","OPTIONS"],allowedHeaders:["Content-Type","Authorization"]})); app.use(express.json({limit:"1mb"}));
app.get("/",(_,res)=>res.json({ok:true,service:"Internadda learning API"})); app.get("/health",(_,res)=>res.json({ok:true}));
async function groq(messages,maxTokens=700,temp=.35){if(!keys.length) throw new Error("GROQ_API_KEY is not configured on the server.");let last;for(const key of keys){try{const c=new Groq({apiKey:key});const r=await c.chat.completions.create({model:MODEL,messages,temperature:temp,max_tokens:maxTokens});const text=r.choices?.[0]?.message?.content||"";if(text)return text;}catch(e){last=e;if(e?.status!==429) break;}}throw last||new Error("AI provider unavailable");}
async function extractText(buffer){const pdf=await getDocument({data:new Uint8Array(buffer)}).promise;let out="";for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const content=await page.getTextContent();out+=content.items.map(x=>x.str).join(" ")+"\n";}return out.trim().slice(0,30000);}
app.post("/parse-resume",upload.single("resume"),async(req,res)=>{try{if(!req.file||req.file.mimetype!=="application/pdf")return res.status(400).json({error:"Please upload a PDF resume."});const text=await extractText(req.file.buffer);if(text.length<40)return res.status(400).json({error:"We could not read enough text from this PDF. Please upload a text-based resume."});res.json({text});}catch(e){console.error(e);res.status(500).json({error:"Unable to parse resume right now."});}});
app.post("/learning/plan",async(req,res)=>{const {name,role,resumeText}=req.body;if(!name||!role||!resumeText)return res.status(400).json({error:"Name, role and resume are required."});const prompt=`Create a concise personalized internship learning plan for ${name}, targeting ${role}. Use only evidence present in the resume. Do not invent skills. Return ONLY valid JSON with keys skills (array max 8), gaps (array max 6), goals (array max 4), roadmap (array of 6 objects with title, reason, priority), summary (string). Resume:\n${String(resumeText).slice(0,24000)}`;try{const raw=await groq([{role:"system",content:"You are a careful learning designer. Never invent candidate facts. Output JSON only."},{role:"user",content:prompt}],1000,.2);const match=raw.match(/\{[\s\S]*\}/);if(!match)throw new Error("Invalid AI response");res.json({plan:JSON.parse(match[0])});}catch(e){console.error(e);res.status(502).json({error:"Could not build the learning plan. Please retry."});}});
app.post("/learning/feedback",async(req,res)=>{const {role,lesson,answer}=req.body;if(!lesson||!answer)return res.status(400).json({error:"Lesson and answer are required."});try{const text=await groq([{role:"system",content:"You are a supportive internship coach. Give concise, specific feedback. Mention one strength, one improvement and one next action. Do not grade harshly. Do not invent facts."},{role:"user",content:`Role: ${role||"student"}\nLesson: ${lesson}\nStudent response: ${answer}`}],350,.3);res.json({feedback:text});}catch(e){res.status(502).json({error:"Feedback is temporarily unavailable."});}});
app.post("/learning/practice",async(req,res)=>{const {role,messages}=req.body;if(!role||!Array.isArray(messages))return res.status(400).json({error:"Role and messages are required."});try{const text=await groq([{role:"system",content:`You are Internadda, a calm internship preparation coach for ${role}. This is practice, not a hiring decision. Ask one useful follow-up at a time. Reference the student's answer. If their answer is weak, briefly teach the missing idea before asking the next question. Keep replies under 120 words.`},...messages.slice(-8)],300,.45);res.json({reply:text});}catch(e){res.status(502).json({error:"Practice service is temporarily unavailable."});}});
const CASHFREE_BASE_URL="https://api.cashfree.com/pg";
app.post("/create-order",async(req,res)=>{const {candidateName,role,email,userId}=req.body;if(!candidateName||!email||!userId)return res.status(400).json({error:"Name, email and account are required."});if(!process.env.CASHFREE_APP_ID||!process.env.CASHFREE_SECRET_KEY)return res.status(503).json({error:"Payment service is not configured yet."});const orderId=`INTA_${Date.now()}_${Math.floor(Math.random()*10000)}`;try{const r=await fetch(`${CASHFREE_BASE_URL}/orders`,{method:"POST",headers:{"x-client-id":process.env.CASHFREE_APP_ID,"x-client-secret":process.env.CASHFREE_SECRET_KEY,"x-api-version":"2023-08-01","Content-Type":"application/json"},body:JSON.stringify({order_id:orderId,order_amount:49,order_currency:"INR",customer_details:{customer_id:userId,customer_name:candidateName.trim(),customer_email:email},order_meta:{return_url:`${process.env.FRONTEND_URL||"http://localhost:5173"}/verify-payment?order_id={order_id}`},order_note:`Internadda personalized learning activation for ${role||"student"}`})});const data=await r.json();if(!r.ok)return res.status(502).json({error:data.message||"Unable to create payment order."});res.json({orderId,paymentSessionId:data.payment_session_id,amount:49});}catch(e){console.error(e);res.status(502).json({error:"Payment service unavailable."})}});
app.post("/verify-order",async(req,res)=>{const {orderId}=req.body;if(!orderId)return res.status(400).json({error:"Order ID is required."});if(!process.env.CASHFREE_APP_ID||!process.env.CASHFREE_SECRET_KEY)return res.status(503).json({error:"Payment service is not configured yet."});try{const r=await fetch(`${CASHFREE_BASE_URL}/orders/${encodeURIComponent(orderId)}`,{headers:{"x-client-id":process.env.CASHFREE_APP_ID,"x-client-secret":process.env.CASHFREE_SECRET_KEY,"x-api-version":"2023-08-01"}});const data=await r.json();res.json({success:data.order_status==="PAID",orderStatus:data.order_status});}catch(e){res.status(502).json({error:"Could not verify payment."})}});
app.listen(PORT,"0.0.0.0",()=>console.log(`Internadda API listening on ${PORT}`));
